# This file was generated by GoReleaser. DO NOT EDIT.
cask "time-pugcha" do
  name "time-pugcha"
  desc "Can i have a coffee break ?"
  homepage "https://github.com/iam-bkpl/time-pugcha"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "time-pugcha"

  on_macos do
    on_intel do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Darwin_x86_64.tar.gz"
      sha256 "f5543e9e326fbe5b3e5947c656b8c92ba0021f44f9f566183902357654f17c3e"
    end
    on_arm do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Darwin_arm64.tar.gz"
      sha256 "15d939c6c0b75abb97dcef28e0cb3222ba8a5e5a3df7587782d63c4e121247f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Linux_x86_64.tar.gz"
      sha256 "17ad80c3ac42d21be445253d64b720474ad65c98b0b9e97c50eb3de856448bb4"
    end
    on_arm do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Linux_arm64.tar.gz"
      sha256 "01f7dec4f6f1f81108ea6b0d5a2f1fd0500e979509816bd51988899f59878893"
    end
  end

  # No zap stanza required
end
