# This file was generated by GoReleaser. DO NOT EDIT.
cask "time-pugcha" do
  name "time-pugcha"
  desc "Can i have a coffee break ?"
  homepage "https://github.com/iam-bkpl/time-pugcha"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "time-pugcha"

  on_macos do
    on_intel do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Darwin_x86_64.tar.gz"
      sha256 "96870e62af7b3beb6aa8af14a5ccdc6e5657d328f75c01a1def6ed1b034d200f"
    end
    on_arm do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Darwin_arm64.tar.gz"
      sha256 "34b5542862e2df048d2f2b75997819bfd50afaee35cfafbeebb21ed3587d28a6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Linux_x86_64.tar.gz"
      sha256 "ebbbaf53300ced0d2dff9b3d68c627ec7b5f6f33b20ef1137fc3aeb08e76f11a"
    end
    on_arm do
      url "https://github.com/iam-bkpl/time-pugcha/releases/download/v#{version}/time-pugcha_Linux_arm64.tar.gz"
      sha256 "999b90d926626411fd0fc8861cd8fa8aad5e5436394c96314b5d7023da17cede"
    end
  end

  # No zap stanza required
end
